import Link from 'next/link'
import Image from 'next/image'
import { ArrowUpRight, Clock, MapPin, Truck, Check, ChevronRight } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { EmailChangeAlert } from '@/components/email-change-alert'
import { LandingHeader, type LandingUser } from '@/components/landing/landing-header'
import { CommandCenter, KitchenPass } from '@/components/landing/product-preview'

export type LandingUserRole = 'owner' | 'rider' | 'user'
export type LandingRestaurant = { id: string; name: string; slug: string; logo_url: string | null; cover_image_url: string | null; description: string | null; cuisine_type: string[] | null; city: string | null; state: string | null; restaurant_settings: unknown }
const SERVICE = [{ eyebrow: '01 / Order desk', title: 'Every order has a place to go.', body: 'Orders land in one queue, with clear ownership from the first tap to the final handoff.' }, { eyebrow: '02 / Kitchen view', title: 'Keep the line moving.', body: 'A live kitchen pass gives your team the next right thing, without noise or guesswork.' }, { eyebrow: '03 / Cash & delivery', title: 'Close the shift cleanly.', body: 'Assign riders, track collections, and see the numbers before the lights go off.' }]
function ctaForRole(role: LandingUserRole, loggedIn: boolean) { if (!loggedIn) return { href: '/signup', label: 'Start free' }; if (role === 'owner') return { href: '/dashboard', label: 'Open dashboard' }; if (role === 'rider') return { href: '/rider', label: 'Open rider sheet' }; return { href: '/onboarding', label: 'Start your restaurant' } }

export function HomeLanding({ user, userRole, isEmailChangePending, onlineRestaurants }: { user: LandingUser | null; userRole: LandingUserRole; isEmailChangePending: boolean; onlineRestaurants: LandingRestaurant[] }) {
  const cta = ctaForRole(userRole, !!user)
  return <div className="min-h-screen overflow-hidden bg-background text-foreground"><LandingHeader user={user} ctaHref={cta.href} ctaLabel={cta.label} />{isEmailChangePending && user && <EmailChangeAlert email={user.email} />}
    <main>
      <section className="landing-hero relative mx-auto max-w-[1440px] px-5 pb-16 pt-14 sm:px-8 lg:px-14 lg:pb-24 lg:pt-24"><div className="landing-grid absolute inset-0 -z-10" /><div className="grid items-end gap-14 lg:grid-cols-[0.92fr_1.08fr] lg:gap-20"><div className="max-w-2xl"><p className="landing-kicker"><span className="size-1.5 rounded-full bg-primary" /> The restaurant operating system</p><h1 className="mt-7 text-balance font-sans text-[3.25rem] font-medium leading-[.94] tracking-[-.07em] sm:text-7xl lg:text-[6.8rem]">The calm behind<br /><span className="font-serif font-normal italic text-primary">the rush.</span></h1><p className="mt-8 max-w-lg text-pretty text-base leading-7 text-muted-foreground sm:text-lg">foodOS puts your orders, kitchen, delivery, and daily numbers in one place — so your team can focus on the food.</p><div className="mt-9 flex flex-col gap-4 sm:flex-row sm:items-center"><Button asChild size="lg" className="h-12 px-6"><Link href={cta.href}>{cta.label}<ArrowUpRight data-icon="inline-end" /></Link></Button><a href="#platform" className="inline-flex items-center gap-2 text-sm text-muted-foreground transition-colors hover:text-foreground">See the system <ChevronRight className="size-4" /></a></div><div className="mt-10 flex items-center gap-3 text-xs text-muted-foreground"><span className="flex -space-x-2"><span className="size-7 rounded-full border-2 border-background bg-primary/70" /><span className="size-7 rounded-full border-2 border-background bg-accent" /><span className="size-7 rounded-full border-2 border-background bg-secondary" /></span><span>Built for independent restaurants<br /><span className="text-foreground">that do more with less.</span></span></div></div><CommandCenter /></div></section>
      <section className="border-y border-border/70"><div className="mx-auto flex max-w-[1440px] flex-col gap-4 px-5 py-6 sm:flex-row sm:items-center sm:justify-between sm:px-8 lg:px-14"><p className="font-mono text-[10px] uppercase tracking-[.2em] text-muted-foreground">One system / all service</p><div className="flex flex-wrap gap-x-6 gap-y-2 font-mono text-[10px] uppercase tracking-[.16em] text-muted-foreground/70"><span>Orders</span><span>Kitchen</span><span>Delivery</span><span>Revenue</span><span>Customers</span></div></div></section>
      <section id="platform" className="mx-auto max-w-[1440px] scroll-mt-24 px-5 py-20 sm:px-8 lg:px-14 lg:py-32"><div className="grid gap-8 lg:grid-cols-[.8fr_1fr]"><div><p className="landing-kicker">The platform</p><h2 className="mt-5 max-w-xl text-balance text-4xl font-medium leading-[1.02] tracking-[-.055em] sm:text-6xl">Your whole restaurant, in focus.</h2></div><p className="max-w-md self-end text-pretty leading-7 text-muted-foreground">No more chasing screenshots, checking three apps, or finding yesterday&apos;s numbers. foodOS gives every shift a shared rhythm.</p></div><div className="mt-14"><KitchenPass /></div></section>
      <section id="service" className="scroll-mt-24 border-y border-border/70"><div className="mx-auto max-w-[1440px] px-5 py-20 sm:px-8 lg:px-14 lg:py-28"><div className="flex flex-col gap-4 border-b border-border pb-8 sm:flex-row sm:items-end sm:justify-between"><div><p className="landing-kicker">How it works</p><h2 className="mt-4 text-4xl font-medium tracking-[-.05em] sm:text-5xl">Designed for the dinner rush.</h2></div><p className="font-mono text-xs text-muted-foreground">LESS ADMIN / MORE SERVICE</p></div><div className="mt-8 grid gap-px overflow-hidden border border-border bg-border md:grid-cols-3">{SERVICE.map((item) => <article key={item.eyebrow} className="bg-background p-7 transition-colors hover:bg-card sm:p-9"><p className="font-mono text-[10px] uppercase tracking-[.18em] text-primary">{item.eyebrow}</p><h3 className="mt-20 max-w-xs text-2xl font-medium leading-tight tracking-[-.04em]">{item.title}</h3><p className="mt-4 max-w-xs text-sm leading-6 text-muted-foreground">{item.body}</p><ChevronRight className="mt-8 size-5 text-primary" /></article>)}</div></div></section>
      <section id="kitchens" className="scroll-mt-24 mx-auto max-w-[1440px] px-5 py-20 sm:px-8 lg:px-14 lg:py-32"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="landing-kicker">Live kitchens</p><h2 className="mt-4 text-4xl font-medium tracking-[-.05em] sm:text-6xl">Open for orders.</h2></div><p className="font-mono text-xs uppercase tracking-[.16em] text-muted-foreground">{onlineRestaurants.length} live now</p></div>{onlineRestaurants.length === 0 ? <div className="mt-12 border border-dashed border-border p-16 text-center"><p className="text-2xl font-medium">No kitchens are taking orders right now.</p><Button asChild className="mt-6"><Link href={cta.href}>{cta.label}</Link></Button></div> : <div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{onlineRestaurants.map((restaurant) => <KitchenCard key={restaurant.id} restaurant={restaurant} />)}</div>}</section>
      <section className="mx-auto max-w-[1440px] px-5 pb-20 sm:px-8 lg:px-14 lg:pb-32"><div className="relative overflow-hidden border border-primary/30 bg-primary px-7 py-14 text-primary-foreground sm:px-14 sm:py-20"><div className="relative max-w-2xl"><p className="font-mono text-[10px] uppercase tracking-[.2em] text-primary-foreground/65">Your next shift</p><h2 className="mt-5 text-balance text-4xl font-medium leading-none tracking-[-.06em] sm:text-7xl">Make busy feel<br /><span className="font-serif italic">beautiful.</span></h2><p className="mt-6 max-w-lg text-base leading-7 text-primary-foreground/75">A sharper system for the restaurants people come back to.</p><Button asChild size="lg" variant="secondary" className="mt-8"><Link href={cta.href}>{cta.label}<ArrowUpRight data-icon="inline-end" /></Link></Button></div></div></section>
    </main><footer className="border-t border-border"><div className="mx-auto flex max-w-[1440px] flex-col gap-5 px-5 py-8 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between sm:px-8 lg:px-14"><p className="font-semibold text-foreground">food<span className="text-primary">OS</span></p><div className="flex flex-wrap gap-5"><a href="#platform">Platform</a><a href="#service">How it works</a><a href="#kitchens">Live kitchens</a><Link href="/login">Log in</Link></div><p>© 2026 foodOS</p></div></footer></div>
}
function kitchenMeta(restaurant: LandingRestaurant) { const raw = restaurant.restaurant_settings as { delivery_fee?: number; min_order_amount?: number }[] | { delivery_fee?: number; min_order_amount?: number } | null; const settings = Array.isArray(raw) ? raw[0] : raw; return { settings, cuisines: (restaurant.cuisine_type || []).slice(0, 3), location: [restaurant.city, restaurant.state].filter(Boolean).join(', ') } }
function KitchenCard({ restaurant }: { restaurant: LandingRestaurant }) { const { settings, cuisines, location } = kitchenMeta(restaurant); return <Link href={`/r/${restaurant.slug}`} className="group overflow-hidden border border-border bg-card transition-colors hover:border-primary/50"><div className="relative h-48 bg-secondary">{restaurant.cover_image_url ? <Image src={restaurant.cover_image_url} alt={restaurant.name} fill className="object-cover transition-transform duration-500 group-hover:scale-105" /> : <div className="flex h-full items-center justify-center text-muted-foreground"><span className="font-serif text-4xl italic">{restaurant.name.slice(0, 1)}</span></div>}</div><div className="p-5"><div className="flex items-start justify-between gap-3"><h3 className="text-xl font-medium tracking-tight">{restaurant.name}</h3><span className="mt-1 size-2 rounded-full bg-primary" /></div>{location && <p className="mt-2 flex items-center gap-1.5 text-sm text-muted-foreground"><MapPin className="size-3.5" />{location}</p>}{cuisines.length > 0 && <div className="mt-4 flex flex-wrap gap-1.5">{cuisines.map((cuisine) => <Badge key={cuisine} variant="secondary" className="rounded-full text-xs">{cuisine}</Badge>)}</div>}<div className="mt-5 flex gap-4 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1"><Truck className="size-3.5" />{settings?.delivery_fee ? `₹${Number(settings.delivery_fee).toFixed(0)} delivery` : 'Delivery'}</span><span className="inline-flex items-center gap-1"><Clock className="size-3.5" />Min ₹{Number(settings?.min_order_amount || 0).toFixed(0)}</span></div></div></Link> }

function Divider() { return null }
