import Link from 'next/link'
import Image from 'next/image'
import { ArrowRight, Clock, MapPin, Truck, Check } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { EmailChangeAlert } from '@/components/email-change-alert'
import { LandingHeader, type LandingUser } from '@/components/landing/landing-header'
import { KitchenPass, TicketStack } from '@/components/landing/product-preview'

export type LandingUserRole = 'owner' | 'rider' | 'user'
export type LandingRestaurant = { id: string; name: string; slug: string; logo_url: string | null; cover_image_url: string | null; description: string | null; cuisine_type: string[] | null; city: string | null; state: string | null; restaurant_settings: unknown }
const SERVICE = [{ title: 'Run every order from one calm view', body: 'Orders arrive clean, move through prep, and stay visible until they reach the customer.', icon: '01' }, { title: 'Give customers a menu worth sharing', body: 'A fast, beautiful ordering page with live prices, photos, delivery rules, and payments.', icon: '02' }, { title: 'Keep riders and cash accountable', body: 'Assign deliveries, track cash collection, and close the shift without the end-of-night scramble.', icon: '03' }]
function ctaForRole(role: LandingUserRole, loggedIn: boolean) { if (!loggedIn) return { href: '/signup', label: 'Start free' }; if (role === 'owner') return { href: '/dashboard', label: 'Open dashboard' }; if (role === 'rider') return { href: '/rider', label: 'Open rider sheet' }; return { href: '/onboarding', label: 'Start your restaurant' } }

export function HomeLanding({ user, userRole, isEmailChangePending, onlineRestaurants }: { user: LandingUser | null; userRole: LandingUserRole; isEmailChangePending: boolean; onlineRestaurants: LandingRestaurant[] }) {
  const cta = ctaForRole(userRole, !!user)
  return <div className="min-h-screen overflow-hidden bg-background text-foreground"><LandingHeader user={user} ctaHref={cta.href} ctaLabel={cta.label} />{isEmailChangePending && user && <EmailChangeAlert email={user.email} />}
    <main>
      <section className="landing-hero relative mx-auto grid max-w-7xl items-center gap-14 px-5 pb-20 pt-16 sm:px-8 lg:grid-cols-[0.88fr_1.12fr] lg:gap-12 lg:pb-28 lg:pt-24"><div className="landing-grid absolute inset-0 -z-10 opacity-60" /><div className="max-w-xl"><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/5 px-3 py-1.5 text-xs font-medium text-primary"><span className="size-1.5 rounded-full bg-primary" /> The operating system for modern restaurants</div><h1 className="text-balance font-sans text-5xl font-semibold leading-[0.98] tracking-[-0.055em] sm:text-7xl">Make service feel <span className="font-serif font-normal italic text-primary">effortless.</span></h1><p className="mt-7 max-w-lg text-pretty text-lg leading-relaxed text-muted-foreground">foodOS brings orders, kitchen operations, delivery, and revenue into one beautifully simple workspace.</p><div className="mt-9 flex flex-wrap items-center gap-4"><Button asChild size="lg"><Link href={cta.href}>{cta.label}<ArrowRight data-icon="inline-end" /></Link></Button><a href="#platform" className="inline-flex items-center gap-2 text-sm font-medium text-muted-foreground hover:text-foreground">See how it works <ArrowRight className="size-4" /></a></div><div className="mt-9 flex flex-wrap gap-x-6 gap-y-2 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1.5"><Check className="size-3.5 text-primary" /> No setup fee</span><span className="inline-flex items-center gap-1.5"><Check className="size-3.5 text-primary" /> Built for busy teams</span><span className="inline-flex items-center gap-1.5"><Check className="size-3.5 text-primary" /> Start in minutes</span></div></div><TicketStack /></section>
      <section className="border-y border-border bg-card/50"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-6 px-5 py-7 sm:px-8"><p className="text-sm text-muted-foreground">Trusted by independent kitchens and growing food brands</p><div className="flex flex-wrap gap-x-8 gap-y-3 font-mono text-xs font-semibold tracking-widest text-muted-foreground/70"><span>NAAN & CO.</span><span>THE DAILY BOWL</span><span>MAISON 24</span><span>SPICE ROUTE</span></div></div></section>
      <section id="platform" className="mx-auto max-w-7xl scroll-mt-24 px-5 py-20 sm:px-8 lg:py-28"><div className="grid items-end gap-8 md:grid-cols-[1fr_0.7fr]"><div><p className="text-sm font-semibold text-primary">One platform. Every shift.</p><h2 className="mt-3 max-w-2xl text-balance text-4xl font-semibold tracking-tight sm:text-5xl">Your best service starts with a clearer picture.</h2></div><p className="max-w-md text-pretty leading-relaxed text-muted-foreground">Stop stitching together chat threads, spreadsheets, and delivery calls. Give your team one shared source of truth.</p></div><div className="mt-14"><KitchenPass /></div></section>
      <section id="service" className="scroll-mt-24 bg-secondary/45"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><div className="max-w-2xl"><p className="text-sm font-semibold text-primary">Everything in sync</p><h2 className="mt-3 text-balance text-4xl font-semibold tracking-tight sm:text-5xl">Less admin. More time for the food.</h2></div><div className="mt-14 grid gap-px overflow-hidden rounded-3xl border border-border bg-border md:grid-cols-3">{SERVICE.map((item) => <article key={item.icon} className="bg-background p-7 sm:p-9"><span className="font-mono text-xs font-semibold text-primary">{item.icon}</span><h3 className="mt-16 text-2xl font-semibold tracking-tight">{item.title}</h3><p className="mt-4 leading-relaxed text-muted-foreground">{item.body}</p><ArrowRight className="mt-8 size-5 text-primary" /></article>)}</div></div></section>
      <section id="kitchens" className="scroll-mt-24 mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-sm font-semibold text-primary">Live kitchens</p><h2 className="mt-3 text-4xl font-semibold tracking-tight sm:text-5xl">Dinner is on.</h2></div><p className="text-sm text-muted-foreground">{onlineRestaurants.length} kitchens accepting orders</p></div>{onlineRestaurants.length === 0 ? <div className="mt-12 rounded-3xl border border-dashed border-border p-16 text-center"><p className="text-2xl font-semibold">No kitchens are taking orders right now.</p><Button asChild className="mt-6"><Link href={cta.href}>{cta.label}</Link></Button></div> : <div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{onlineRestaurants.map((restaurant) => <KitchenCard key={restaurant.id} restaurant={restaurant} />)}</div>}</section>
      <section className="mx-auto max-w-7xl px-5 pb-20 sm:px-8 lg:pb-28"><div className="relative overflow-hidden rounded-[2rem] bg-primary px-7 py-14 text-primary-foreground sm:px-14 sm:py-20"><div className="relative max-w-2xl"><p className="text-sm font-semibold text-primary-foreground/70">Ready when you are</p><h2 className="mt-4 text-balance text-4xl font-semibold tracking-tight sm:text-6xl">Build a better shift.</h2><p className="mt-5 max-w-lg text-lg leading-relaxed text-primary-foreground/75">Join the restaurants making every service calmer, faster, and more profitable.</p><Button asChild size="lg" variant="secondary" className="mt-8"><Link href={cta.href}>{cta.label}<ArrowRight data-icon="inline-end" /></Link></Button></div></div></section>
    </main><footer className="border-t border-border"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-5 py-8 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between sm:px-8"><p className="font-semibold text-foreground">foodOS</p><div className="flex flex-wrap gap-5"><a href="#platform">Platform</a><a href="#service">How it works</a><a href="#kitchens">Live kitchens</a><Link href="/login">Log in</Link></div><p>© 2026 foodOS</p></div></footer></div>
}

function kitchenMeta(restaurant: LandingRestaurant) { const raw = restaurant.restaurant_settings as { delivery_fee?: number; min_order_amount?: number }[] | { delivery_fee?: number; min_order_amount?: number } | null; const settings = Array.isArray(raw) ? raw[0] : raw; return { settings, cuisines: (restaurant.cuisine_type || []).slice(0, 3), location: [restaurant.city, restaurant.state].filter(Boolean).join(', ') } }
function KitchenCard({ restaurant }: { restaurant: LandingRestaurant }) { const { settings, cuisines, location } = kitchenMeta(restaurant); return <Link href={`/r/${restaurant.slug}`} className="group overflow-hidden rounded-2xl border border-border bg-card transition-all hover:-translate-y-1 hover:border-primary/40 hover:shadow-xl hover:shadow-primary/5"><div className="relative h-48 bg-secondary">{restaurant.cover_image_url ? <Image src={restaurant.cover_image_url} alt={restaurant.name} fill className="object-cover transition-transform duration-500 group-hover:scale-105" /> : <div className="flex h-full items-center justify-center text-muted-foreground"><span className="font-serif text-4xl italic">{restaurant.name.slice(0, 1)}</span></div>}</div><div className="p-5"><div className="flex items-start justify-between gap-3"><h3 className="text-xl font-semibold tracking-tight">{restaurant.name}</h3><span className="mt-1 size-2 rounded-full bg-primary" /></div>{location && <p className="mt-2 flex items-center gap-1.5 text-sm text-muted-foreground"><MapPin className="size-3.5" />{location}</p>}{cuisines.length > 0 && <div className="mt-4 flex flex-wrap gap-1.5">{cuisines.map((cuisine) => <Badge key={cuisine} variant="secondary" className="rounded-full text-xs">{cuisine}</Badge>)}</div>}<div className="mt-5 flex gap-4 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1"><Truck className="size-3.5" />{settings?.delivery_fee ? `₹${Number(settings.delivery_fee).toFixed(0)} delivery` : 'Delivery'}</span><span className="inline-flex items-center gap-1"><Clock className="size-3.5" />Min ₹{Number(settings?.min_order_amount || 0).toFixed(0)}</span></div></div></Link> }
