import { Check, Clock3, MoreHorizontal, TrendingUp, Utensils } from 'lucide-react'

const orders = [
  { id: '#1042', name: 'Ayesha Khan', items: 'Butter chicken · Garlic naan ×2', total: '₹420', status: 'Preparing', tone: 'bg-accent text-accent-foreground' },
  { id: '#1041', name: 'Rahul Mehta', items: 'Paneer tikka · Masala coke', total: '₹310', status: 'Ready', tone: 'bg-primary text-primary-foreground' },
  { id: '#1040', name: 'Priya Shah', items: 'Hyderabadi biryani · Raita', total: '₹280', status: 'On the way', tone: 'bg-secondary text-secondary-foreground' },
]

export function TicketStack() {
  return <div className="relative mx-auto flex min-h-[420px] max-w-[560px] items-center justify-center"><div className="absolute inset-x-6 top-8 h-72 rotate-[-4deg] rounded-[2rem] border border-primary/10 bg-primary/5" /><div className="absolute inset-x-3 top-4 h-72 rotate-[3deg] rounded-[2rem] border border-primary/10 bg-card/80" /><div className="relative w-full overflow-hidden rounded-[2rem] border border-border bg-card p-5 shadow-2xl shadow-primary/10"><div className="flex items-center justify-between border-b border-border pb-5"><div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-xl bg-primary/10 text-primary"><Utensils /></div><div><p className="text-sm font-semibold">Good morning, Farhan</p><p className="text-xs text-muted-foreground">Tuesday, 20 August · Main kitchen</p></div></div><MoreHorizontal className="text-muted-foreground" /></div><div className="grid grid-cols-3 gap-3 py-5"><div><p className="text-xs text-muted-foreground">Today&apos;s sales</p><p className="mt-1 text-xl font-semibold">₹24,680</p><p className="mt-1 flex items-center gap-1 text-xs text-primary"><TrendingUp className="size-3" /> 18.4%</p></div><div><p className="text-xs text-muted-foreground">Orders</p><p className="mt-1 text-xl font-semibold">48</p><p className="mt-1 text-xs text-muted-foreground">+6 from yesterday</p></div><div><p className="text-xs text-muted-foreground">Avg. prep</p><p className="mt-1 text-xl font-semibold">18m</p><p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><Clock3 className="size-3" /> 4m faster</p></div></div><div className="flex items-center justify-between border-b border-border pb-3"><p className="text-sm font-semibold">Live orders</p><span className="flex items-center gap-1.5 text-xs text-primary"><span className="size-1.5 rounded-full bg-primary" /> Kitchen live</span></div><div className="flex flex-col divide-y divide-border">{orders.map((order) => <div key={order.id} className="flex items-center gap-3 py-4"><div className="flex size-9 shrink-0 items-center justify-center rounded-lg bg-secondary text-xs font-semibold">{order.id.slice(1)}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{order.name}</p><p className="truncate text-xs text-muted-foreground">{order.items}</p></div><div className="text-right"><p className="text-sm font-semibold">{order.total}</p><span className={`mt-1 inline-flex rounded-full px-2 py-0.5 text-[10px] font-medium ${order.tone}`}>{order.status}</span></div></div>)}</div></div></div>
}

export function KitchenPass() {
  return <div className="grid gap-4 md:grid-cols-[1.2fr_0.8fr]"><div className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Order flow</p><p className="text-xs text-muted-foreground">Everything moving, nothing missed</p></div><span className="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-medium text-primary">Live</span></div><div className="mt-6 flex items-end gap-2"><div className="h-20 flex-1 rounded-t-lg bg-primary/30" /><div className="h-28 flex-1 rounded-t-lg bg-primary/45" /><div className="h-24 flex-1 rounded-t-lg bg-primary/60" /><div className="h-36 flex-1 rounded-t-lg bg-primary" /><div className="h-32 flex-1 rounded-t-lg bg-primary/70" /><div className="h-44 flex-1 rounded-t-lg bg-primary" /><div className="h-40 flex-1 rounded-t-lg bg-primary/80" /></div><div className="mt-3 flex justify-between text-[10px] text-muted-foreground"><span>10am</span><span>2pm</span><span>6pm</span><span>Now</span></div></div><div className="rounded-2xl border border-border bg-card p-5"><p className="text-sm font-semibold">Kitchen pulse</p><p className="mt-1 text-xs text-muted-foreground">Current service status</p><div className="mt-7 flex items-center gap-3"><div className="flex size-11 items-center justify-center rounded-full bg-primary/10 text-primary"><Check /></div><div><p className="text-2xl font-semibold">92%</p><p className="text-xs text-muted-foreground">orders on time</p></div></div><div className="mt-6 h-2 overflow-hidden rounded-full bg-secondary"><div className="h-full w-[92%] rounded-full bg-primary" /></div></div></div>
}
